language: dart
dart:
  - "2.12.3"

install:
  # https://flutter.dev/docs/get-started/web
  - echo "Configure AWSCLI"
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - echo "Configure Flutter"
  - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.0.6-stable.tar.xz
  - tar xf flutter_linux_2.0.6-stable.tar.xz
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter config --enable-web
  - flutter doctor

script:
  - echo "Building..."
  - flutter build web
  - ls
