language: dart
dart:
  - "2.12.3"

install:
  # https://flutter.dev/docs/get-started/web
  - echo "Configure Flutter"
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter upgrade
  - flutter version 2.0.6
  - flutter config --enable-web
  - flutter doctor

script:
  - echo "Building..."
  - flutter build web
  - ls
